### ISSUE TITLE
Any support for Nethunter Arm based?

### ISSUE THREAD

**Issue by jepunband** [WayzDev/Kage#24]
hello, Any support for Nethunter Arm based?

**Comment by necrose99** [comment]
#21

https://www.electron.build/multi-platform-build 
i've built for pentoo on arm64 , app-image or otherwise tarball. 
electron-builder -mwl will build even for MACOS however since I haven't a mac.... 
Mac/WINDOWS/Linux... 
--arm64  --armv7l ? or ssomething specfic to arm.. , 


yarn run build -l --arm64  --armv7l  force targets.

**Comment by necrose99** [comment]
#21

**Comment by jepunband** [comment]
hi .. for armv device

**Comment by necrose99** [comment]
@jepunband  yarn run build -l  --armv7l force targets

**Comment by necrose99** [comment]
yarn run build -l --arm64 --armv7l  @jepunband  

**_package.json_**  bit of [leafpad ](http://tarot.freeshell.org/leafpad/) action on linux desktop ,  

```
            "target": [
                "AppImage" ``
```
(https://www.electron.build/configuration/linux) wish ebuild was a target (give me a script to run in gentoo/build/emerge)   however `"AppImage`  `"deb"`  `"rpm"`  '"tar.xz"  'or alike  if you want a deb vs app image you can search in [leafpad ](http://tarot.freeshell.org/leafpad/)


**[gentoo arm64-rpi4](https://github.com/sakaki-/gentoo-on-rpi-64bit)  , ran  yarn run build -l --arm64 --armv7l force targets.**
out came my tarballs as asked for ... 

(gentoo i could make an rpm based ebuild inherit rpm as an admin some the ebuilds are bit beyond but rpm/deb to installed gentoo pkg is often beginner friendly  enough..   )

**Comment by Zerx0r** [comment]
Closing the issue
